on: workflow_dispatch

name: CD

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      crate-name: ${{ steps.crate-info.outputs.package_name }}
      crate-version: ${{ steps.crate-info.outputs.package_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get Crate Info
        id: crate-info
        uses: nicolaiunrein/cargo-get@master

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          name: Release v${{ steps.crate-info.outputs.package_version }}
          tag_name: v${{ steps.crate-info.outputs.package_version }}

  assets:
    name: Build & Upload Release Assets
    needs: release
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
            archive: tar.gz

          - target: aarch64-apple-darwin
            os: macos-latest
            archive: tar.gz

          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            archive: tar.gz

          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            archive: tar.gz

          - target: x86_64-pc-windows-msvc
            os: windows-latest
            archive: zip

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Install Cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Cross Build
        run: cross build --locked --verbose --release --target=${{ matrix.target }}

      - name: Create Unix Archives
        if: ${{ !startsWith(matrix.os, 'windows') }}
        run: |
          mkdir -p dist
          tar -czf dist/${{ needs.release.outputs.crate-name }}-${{ needs.release.outputs.crate-version }}-${{ matrix.target }}.${{ matrix.archive }} \
          -C target/${{ matrix.target }}/release ${{ needs.release.outputs.crate-name }}

      - name: Create Windows Archive
        if: startsWith(matrix.os, 'windows')
        run: |
          New-Item -Name "dist" -ItemType Directory
          Compress-Archive `
            -Path target\${{ matrix.target }}\release\${{ needs.release.outputs.crate-name }}.exe `
            -DestinationPath dist\${{ needs.release.outputs.crate-name }}-${{ needs.release.outputs.crate-version }}-${{ matrix.target }}.${{ matrix.archive }}

      - name: Upload Archives
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.release.outputs.crate-version }}
          files: dist/${{ needs.release.outputs.crate-name }}-${{ needs.release.outputs.crate-version }}-${{ matrix.target }}.${{ matrix.archive }}

      - name: Install Cargo Deb
        if: contains(matrix.target, 'linux')
        run: cargo install cargo-deb

      - name: Build Debian Package
        if: contains(matrix.target, 'linux')
        run: cargo deb --output dist/${{ needs.release.outputs.crate-name }}-${{ needs.release.outputs.crate-version }}-${{ matrix.target }}.deb

      - name: Upload Debian Package
        if: contains(matrix.target, 'linux')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.release.outputs.crate-version }}
          files: dist/${{ needs.release.outputs.crate-name }}-${{ needs.release.outputs.crate-version }}-${{ matrix.target }}.deb