on: workflow_dispatch

name: CD

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      bin-name: ${{ steps.bin-name.outputs.bin-name }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract Version
        id: version
        run: |
          VERSION=$(grep '^version = ' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Extract Binary Name
        id: bin-name
        run: |
          BIN_NAME=$(grep '^name = ' Cargo.toml | head -1 | sed 's/name = "\(.*\)"/\1/')
          echo "bin-name=$BIN_NAME" >> $GITHUB_OUTPUT
      - uses: taiki-e/create-gh-release-action@v1
        with:
          title: Release v$version
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: refs/tags/v${{ steps.version.outputs.version }}

  upload-archives:
    name: Build & Upload Archives
    needs: create-release
    strategy:
      matrix:
        include:
          - target: universal-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Building ${{ matrix.target }}
        run: echo "${{ matrix.target }}"
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ${{ needs.create-release.outputs.bin-name }}
          target: ${{ matrix.target }}
          tar: unix
          zip: windows
          include: LICENSE-APACHE.md,LICENSE-MIT.md
          ref: refs/tags/v${{ needs.create-release.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-deb:
    name: Build & Upload Debian Package
    needs: create-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1.0.1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-deb
      - uses: actions-rs/cargo@v1
        with:
          command: deb
          args: --target=${{ matrix.target }}
      - name: Upload Debian Package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DEB_FILE=$(find target/${{ matrix.target }}/debian -name "*.deb")
          gh release upload v${{ needs.create-release.outputs.version }} "$DEB_FILE"